### ISSUE TITLE
Month change listner

### ISSUE THREAD

**Issue by zeero0** [AppliKeySolutions/CosmoCalendar#10]
How can we detect month change? Is there any listener?

**Comment by AppliKeySolutions** [comment]
There is no currently a listener to detect a month change. However, we can put it on our backlog.

**Comment by zeero0** [comment]
I have created one in **MonthHolder** which works fine for Activity but crashes on using in Fragment.

**Comment by AppliKeySolutions** [comment]
Added in 1.0.2 version
