### ISSUE TITLE
Drag START_RANGE_DAY or END_RANGE_DAY

### ISSUE THREAD

**Issue by vcanovas** [AppliKeySolutions/CosmoCalendar#5]
Hi,
this library is great. It's possible to drag the FIRST_RANGE_DAY or END_RANGE_DAY to extend or reduce the selected days?

**Comment by AppliKeySolutions** [comment]
Hi,

There is no such functionality in current state and we think that it will be not an easy task to implement with existing architecture. 

BR,
Applikey team
