### ISSUE TITLE
Disable day within selected range

### ISSUE THREAD

**Issue by leonardo2204** [AppliKeySolutions/CosmoCalendar#7]
Should the user be allowed to select a range date, when within it, there is a disabled (or more than one) disabled day ?

For instance:
![screenshot_1507162832](https://user-images.githubusercontent.com/1509421/31205802-1b5fc524-a94a-11e7-994d-60260d8fa498.png)

October 4th is disabled

I'd gladly drop a PR fixing it (if it's a bug)

**Comment by AppliKeySolutions** [comment]
Hi,

Sounds like a bug. We will be happy to see your PR. 

BR,

Applikey team

**Comment by leonardo2204** [comment]
Sure, no problem. What's the expected behavior here ? Not allow the user to select future dates after the disabled day(s) ?

**Comment by AppliKeySolutions** [comment]
Yes, you are 100% right!

**Comment by leonardo2204** [comment]
Cool, see if I can drop a PR this week

**Comment by kanujgit** [comment]
if u want this feature just add the code in **CalanderView** class  in getSelectedDays() functions
` if(!day.isDisabled()){
                        selectedDays.add(day);
                    }else {
                        selectedDays.clear();
                        clearSelections();
                    }`

**Comment by kanujgit** [comment]
if u want this feature just add the code in CalanderView class in getSelectedDays() functions

` /**
     * Returns all selected days
     *
     * @return
     */
    public List<Day> getSelectedDays() {
        List<Day> selectedDays = new ArrayList<>();
        for (Iterator<Month> monthIterator = monthAdapter.getData().iterator(); monthIterator.hasNext(); ) {
            Month month = monthIterator.next();
            for (Iterator<Day> dayIterator = month.getDaysWithoutTitlesAndOnlyCurrent().iterator(); dayIterator.hasNext(); ) {
                Day day = dayIterator.next();
                //     Log.e("day",day.getCalendar().getTime()+"");
                if (selectionManager.isDaySelected(day)) {
                    if(!day.isDisabled()){

                        selectedDays.add(day);
                        Log.e("seda",day+"");

                    }else {
                        selectedDays.clear();
                        clearSelections();
                    }


                }
            }
        }
        return selectedDays;
    }`
