### ISSUE TITLE
Disable click on CalendarView

### ISSUE THREAD

**Issue by zeero0** [AppliKeySolutions/CosmoCalendar#8]
Is there a way to disable **click** on CalendarView?

**Comment by leonardo2204** [comment]
You mean not being able to select any date or all gestures (swiping, changing month etc ?)

**Comment by zeero0** [comment]
Yeah only disable date selection.

**Comment by AppliKeySolutions** [comment]
Hi,

We will disable it.

**Comment by zeero0** [comment]
Great!
I will be waiting for that.

Thanks
