### ISSUE TITLE
 ConcurrentModificationException

### ISSUE THREAD

**Issue by mg931** [ApplikeySolutions/CosmoCalendar#9]
Hi, 

Thanks for putting together this very useful library. 

I encountered this error when rapidly scrolling through months with the calendar in horizontal configuration and the selection type set to multiple. To be honest this was more of a stress test, but i ended up with this exception... 

`java.util.ConcurrentModificationException ·
Raw
ArrayList.java:573java.util.ArrayList$ArrayListIterator.next	
CalendarView.java:573com.applikeysolutions.cosmocalendar.view.CalendarView.getSelectedDays	
CalendarView.java:628com.applikeysolutions.cosmocalendar.view.CalendarView.onDaySelected	
MultipleSelectionManager.java:38com.applikeysolutions.cosmocalendar.selection.MultipleSelectionManager.toggleDay	
DayDelegate.java:38com.applikeysolutions.cosmocalendar.view.delegate.DayDelegate$1.onClick	
View.java:5226android.view.View.performClick	
View.java:21266android.view.View$PerformClick.run	
Handler.java:739android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:168android.os.Looper.loop	
ActivityThread.java:5845android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:797com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:687com.android.internal.os.ZygoteInit.main`

There is also noticeable lag when scrolling quickly through the months - i wondered if it's possible to set a limit on how far in the future/past the user is able to scroll? For example, can I limit the calendar to scroll no further than 1 year in the future? 

Many thanks in advance

**Comment by AppliKeySolutions** [comment]
Hi,

Thanks! We will fix it soon.
